<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div id="content" class="row">

</div>


<script>
<?php $this->inlineScript()->captureStart() ;?>  

var controllers = [
    '<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'dashboard'), 'default', true)?>',
    '<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'dashboard'), 'default', true)?>',
    '<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'dashboard'), 'default', true)?>',
    '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'dashboard'), 'default', true)?>'  
];

for(var i = 0; i < controllers.length; i++) {

$.ajax({
        url: controllers[i]
    }).done( function(data) {
        $('#content').append(data);
    }).fail( function() {
        alert("Error while loading dashboard on path " . controllers[i]);
    });
}
    
<?php $this->inlineScript()->captureEnd() ;?>
</script>
