<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div id="clients" class="col-lg-4 col-md-6"></div>
    <div id="services" class="col-lg-4 col-md-6"></div>
    <div id="members" class="col-lg-4 col-md-6"></div>
    <div id="users" class="col-lg-4 col-md-6"></div>
    
</div>


<script>
<?php $this->inlineScript()->captureStart() ;?>  

    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'dashboard'), 'default', true)?>'
    }).done( function(data) {
        $('#clients').html(data);
    }).fail( function() {
        alert("Error while loading dashboard clients.");
    });
    
    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'dashboard'), 'default', true)?>'
    }).done( function(data) {
        $('#members').html(data);
    }).fail( function() {
        alert("Error while loading dashboard members.");
    });
    
    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'dashboard'), 'default', true)?>',
    }).done( function(data) {
        $('#services').html(data);
    }).fail( function() {
        alert("Error while loading dashboard services.");
    });
    
    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'dashboard'), 'default', true)?>'
    }).done( function(data) {
        $('#users').html(data);
    }).fail( function() {
        alert("Error while loading dashboard users");
    });

<?php $this->inlineScript()->captureEnd() ;?>
</script>
