<?php

$this->headTitle('Clients');

?>
<div class="page-header">
  <h1>Clients</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
                                    <button data-action="save-order" class ="btn btn-success" style="display:none"><i class="glyphicon glyphicon-save"></i> Save order</button>
                                    <button data-action="toggle-sort" class="btn btn-default"><i class="glyphicon glyphicon-list"></i> Change order</button>
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'add'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add client</a>
				</div>
			</div>
			<div class="panel-body">
				
				<table id="table-rows" class="table table-striped table-hover">
					<thead>
						<tr>
                                                    <th></th>
							<th class="text-center">Img</th>
							<th class="text-center">Status</th>
							<th>Name</th>
							<th>Description</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
						<?php 
						foreach ($this->clients as $client) {
							if ($client['status'] == Application_Model_DbTable_CmsClients::STATUS_DISABLED) {
							?>
						<tr data-client-id="<?php echo $this->escape($client['id']);?>" class="danger">
                                                    <td class="text-center"><i  data-action="sort"  style="display:none; cursor: pointer;" class="glyphicon glyphicon-list"></i></td>
							<td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->clientImgUrl($client);?>"></td>
							<td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
							<td><?php echo $this->escape($client['name']);?></td>
							<td><?php echo $this->escape($client['description']);?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
                                                                            href="<?php echo $this->url( array('controller' => 'admin_clients', 'action' => 'edit', 'id' => $client['id']), 'default', true ) ;?>"
                                                                            type="button" class="btn btn-default" title="edit">
                                                                            <i class="glyphicon glyphicon-pencil"></i>
                                                                        </a>
									<button data-client-info="<?php echo $this->escape($client['name']) ;?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                                                        <button data-client-info="<?php echo $this->escape($client['name']) ;?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								</div>
							</td>
						</tr>
							<?php
							} else {
							?>
						<tr data-client-id="<?php echo $this->escape($client['id']);?>">
                                                    <td class="text-center"><i data-action="sort" style="display:none; cursor: pointer;" class="glyphicon glyphicon-list"></i></td>
							<td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->clientImgUrl($client);?>"></td>
							<td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
							<td><?php echo $this->escape($client['name']);?></td>
							<td><?php echo $this->escape($client['description']);?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
                                                                            href="<?php echo $this->url( array('controller' => 'admin_clients', 'action' => 'edit', 'id' => $client['id']), 'default', true ) ;?>"
                                                                            type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-client-info="<?php echo $this->escape($client['name']) ;?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                                                        <button data-client-info="<?php echo $this->escape($client['name']) ;?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								</div>
							</td>
						</tr>
							<?php
							}
							?>
						
							<?php
						}
						?>
						
					</tbody>
				</table>
				
				
				
			</div>
		</div>
	</div>
</div>

<form id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog" method="post" action="<?php echo $this->url( array('controller' => 'admin_clients', 'action' => 'delete'), 'default', true) ;?>">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete client</h4>
      </div>
      <div class="modal-body">
          <p>Are you sure you want to delete client <span id="delete-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger">Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<form id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog" method="post" action="<?php echo $this->url( array('controller' => 'admin_clients', 'action' => 'disable'), 'default', true) ;?>">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable client</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable client <span id="disable-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger">Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<form id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog" method="post" action="<?php echo $this->url( array('controller' => 'admin_clients', 'action' => 'enable'), 'default', true) ;?>">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable client</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to enable <span id="enable-user"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success">Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'updateorder' ), 'default', true) ;?>" style="display:none;" id="save-order-form">
    <input type="hidden" name="task" value="saveorder">
    <input type="hidden" name="sorted_ids" value="">
</form>


<?php
$this->headLink()->appendStylesheet($this->baseUrl("/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css"));
$this->inlineScript()->appendFile($this->baseUrl("/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js"));
?>
<script>
<?php $this->inlineScript()->captureStart() ;?>    
    
    $('#table-rows').on('click', "[data-action='delete']", function(e) {
        e.preventDefault();
        e.stopPropagation();
        
        var target = $(this).is("[data-action='delete']") ? $(this) : $(this).closest("[data-action='delete']");
        
        
        var clientId = target.attr('data-client-id');
        var clientInfo = target.attr('data-client-info');
        
        $('#delete-warning-dialog [name = "id"] ').val(clientId) //alternativni nacin
        $('#delete-user').text(clientInfo);
        $('#delete-warning-dialog').modal('show');
        
    });
    
    $('#table-rows').on('click', "[data-action='disable']", function(e) {
        e.preventDefault();
        e.stopPropagation();
        
        var target = $(this).is("[data-action='disable']") ? $(this) : $(this).closest("[data-action='disable']");
        var clientId = target.attr('data-client-id');
                var clientInfo = target.attr('data-client-info');
                
        $('#disable-warning-dialog [name = "id"] ').val(clientId) //alternativni nacin
        $('#disable-user').text(clientInfo);
        $('#disable-warning-dialog').modal('show');
        
    });
    
    
    $('#table-rows').on('click', "[data-action='enable']", function(e) {
        e.preventDefault();
        e.stopPropagation();
        
        var target = $(this).is("[data-action='enable']") ? $(this) : $(this).closest("[data-action='enable']");
        var clientId = target.attr('data-client-id');
        var clientInfo = target.attr('data-client-info');

        $('#enable-warning-dialog [name = "id"] ').val(clientId) //alternativni nacin
        $('#enable-user').text(clientInfo);
        $('#enable-warning-dialog').modal('show');
        
    });
    
    
    $("[data-action='toggle-sort']").on('click', function(e) {
        e.preventDefault();
        e.stopPropagation;
        var target = $(this).is("[data-action='toggle-sort']") ? $(this) : $(this).closest("[data-action='toggle-sort']");
        var sortableTbody = $("#table-rows > tbody");
        
        if (target.hasClass('active')) {
            target.removeClass('active');    
            target.html('<i class="glyphicon glyphicon-list"></i> Change order');
            sortableTbody.sortable('destroy');
            sortableTbody.html(sortableTbody.data('oldHtml'));
            sortableTbody.find('[data-action="sort"]').hide();
            $('[data-action="save-order"]').hide();
                    
        } else {
            target.addClass('active');
            target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');
            sortableTbody.data("oldHtml", sortableTbody.html());
            sortableTbody.sortable({
                handle: '[data-action="sort"]'
            });
            sortableTbody.find('[data-action="sort"]').show();
            $('[data-action="save-order"]').show();
        }
    });
    
    $("[data-action='save-order']").on('click', function(e) {
        e.preventDefault;
        e.stopPropagation;
        var clientSortedIds = $('#table-rows > tbody').sortable('toArray', {
            attribute: "data-client-id"
        });
        var saveOrderForm = $('#save-order-form');
        saveOrderForm.find('[name="sorted_ids"]').val( clientSortedIds.join(","));
        saveOrderForm.trigger('submit');
    });
    
<?php $this->inlineScript()->captureEnd() ;?>
</script>