<?php 
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']); 
?>

<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span><?php echo $this->escape($sitemapPage['title']) ;?></span> 
						<small><?php echo $this->escape($sitemapPage['description']) ;?></small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<!-- About -->
				<div class="row">
					<div class="col-md-8">
						<!-- About company -->
                                                <div class="block">
                                                    
                                                    <?php echo $sitemapPage['body'] ;?>
                                                    
                                                </div>
						<!-- The team -->
						
						<!-- Quotes -->
						
					</div>
					<!-- sidebar -->
					<div class="col-md-4 sidebar sidebar-right">
						<div class="inner">
							<div class="block">
                                                            <?php if(!empty($this->sitemapPageLinks)) { ?>
								<h3 class="block-title sub-title">
									<span>About Menu</span>
								</h3>
								<ul class="nav nav-list secondary-nav">
                                                                    <?php foreach($this->sitemapPageLinks as $sitemapPageLink) {;?>
									<li>
										<a href="<?php echo $this->sitemapPageUrl($sitemapPageLink['id']) ;?>"><i class="fa fa-chevron-right"></i> <?php echo $this->escape($sitemapPageLink['short_title']) ;?></a>
									</li>
                                                                        <?php if( !empty($this->sitemapPageChildLinks) && $this->sitemapPageChildLinks[0]["parent_id"] == $sitemapPageLink["id"]) { ?>
                                                                        <ul class="nav">
                                                                            <?php foreach($this->sitemapPageChildLinks as $childLink) { ?>
                                                                            <li>
                                                                            <a href="<?php echo $this->sitemapPageUrl($childLink['id']) ;?>"><i class="fa fa-chevron-right"></i> <?php echo $this->escape($childLink['short_title']) ;?></a>
                                                                            </li>
                                                                            <?php } ?>
                                                                        </ul>
                                                                        <?php } ?>
                                                                    <?php } ?>
								</ul>
                                                            <?php } ?>
							</div>
							
							
						</div>
					</div>
				</div>
			</div>
		</div>