<script>
    <?php $this->inlineScript()->captureStart() ;?>
    var ime = 'hello world';
    var starost = 30;
    
    var polaznici = ['ime1', 'ime2', 'ime3'];
    
//    for(var index in polaznici) {
        
//        alert( ( parseInt(index) + 1 ) + " " + polaznici[index]);
//        console.log( ( parseInt(index) + 1 ) + " " + polaznici[index]);
        
//    }
    
//    alert(polaznici[0]);
    
//    alert(ime);
    
//    console.log(polaznici);
    
    var polaznik = { 'ime' : 'ime1', "kljuc" : 2, prezime : 'prezime', starost: 30};
    
//    alert(polaznik.ime);

    var cubes = {
        name: 'Cubes d.o.o',
        address: 'Bul. Mihajla Pupina 181',
        courses: [
            {
                name: 'PHP',
                students: {
                    php01: 'Aleksandar',
                    php02: 'Natasa',
                    php03: 'Aleksandra'
                }
            },
            {
                name: 'iOS',
                students: {
                    ios01: 'ime1',
                    ios02: 'neko',
                    ios03: 'polaznik'
                }
            }
        ]
    };
    
//    alert(cubes.courses[0].students.php01);
//    
//    alert(cubes['courses'][0]['students']['php02']);

//    console.log(cubes);

//for(var key in polaznik)
//    console.log(key + ' -> ' + polaznik[key])

var doubleTestNumber = 77;

function testF(testNumber) {
    var doubleTestNumber = testNumber * 2;
    
//  console.log('Calling function testF ' + doubleTestNumber + '!' );  
};

testF(2);
testF(4);
testF(5);
testF(1);
testF(2);

//console.log('doubleTestNumber is: ' + doubleTestNumber);

var testF2 = function() {
    console.log("Calling function");
};

testF2();

//Object constructor
function Polaznik(ime, prezime, starost) {
    
    this.ime = ime;
    this.prezime = prezime;
    this.starost = starost;
    
    this.predstaviSe = function() {
        return 'Ja sam ' + this.ime + ' ' + this.prezime + ' i imam ' + this.starost + ' godina.';
    }
    
}

var p1 = new Polaznik('ime1', 'prezime1', 63);
var p2 = new Polaznik('ime2', 'prezime2', 42);
var p3 = new Polaznik('ime3', 'prezime3', 22);
var p4 = new Polaznik('ime4', 'prezime4', 55);

console.log(p1.predstaviSe());
console.log(p2.predstaviSe());
console.log(p3.predstaviSe());
console.log(p4.predstaviSe());

p4.getIme = function() {
    return this.ime;
}


window;
window.screen;
screen;

window.location;
location;

//setTimeout( function() {
//    location.href = "http://www.google.com";
//} , 5000); 

<?php $this->inlineScript()->captureEnd() ;?>

</script>