<?php

    $this->headTitle('Members - Edit Member');
            
?>


<div class="page-header">
  <h1>Members <small>Edit Member</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
            
                
                <div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'index'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-arrow-left"></i> Back to all members</a>
                </div>
            </div>
            
            <div class="panel-body">
                
                <!----form start-------> 


                <form class="form-horizontal">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit member</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="first_name">First name</label>  
                            <div class="col-md-4">
                                <input id="first_name" name="first_name" placeholder="enter member's first name" class="form-control input-md" required="" type="text">
                                <span class="help-block">Min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="last_name">Last name</label>  
                            <div class="col-md-4">
                                <input id="last_name" name="last_name" placeholder="enter member's last name" class="form-control input-md" required="" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                <input id="email" name="email" placeholder="enter member's email" class="form-control input-md" required="" type="text">
                                <span class="help-block">user@domain</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="work_title">Work title</label>  
                            <div class="col-md-4">
                                <input id="work_title" name="work_title" placeholder="enter member's work title" class="form-control input-md" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="resume">Resume</label>
                            <div class="col-md-4">                     
                                <textarea class="form-control" id="resume" name="resume"></textarea>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Default"></label>
                            <div class="col-md-8">
                                <button id="button1id" name="button1id" class="btn btn-default">Cancel</button>
                                <button id="button2id" name="button2id" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>




                <!----form end------>
                
                
                
            </div>
        </div>
    </div>

</div>