<?php

$datatableJson = array(
    'draw' => $this->draw,
    'recordsTotal' => $this->usersTotal,
    'recordsFiltered' => $this->usersFilteredCount,
    'data' => array()
);

foreach($this->users AS $user) {
    $row = array();
    
//    $row['DT_RowData'] = array(
//        'user-id' => $user['id']
//    );
    
    $row['DT_RowAttr'] = array(
        'data-user-id' => $user['id'],
        'title' => $user['username']
    );
    
    if($user['status'] == Application_Model_DbTable_CmsUsers::STATUS_DISABLED) {
        $row['DT_RowClass'] = 'danger'; //za dodavanje klase u row-u tabele (da se vrati ono da se zacrveni red disable-ovanog user-a)
    }
    
     foreach($this->columns AS $columnName) {
        
        if($columnName == 'status') {
            
            if($user['status'] == Application_Model_DbTable_CmsUsers::STATUS_ENABLED) {
                $row[] = '<span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span>';
            } else {
                $row[] = '<span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove">';
            }
            
        } else if($columnName == 'actions') {
            $this->placeholder('actions')->exchangeArray(array());
            
            $this->placeholder('actions')->captureStart();
            
            if($user['status'] == Application_Model_DbTable_CmsUsers::STATUS_ENABLED) {
                ?>
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                            <a 
                                    href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
                                    type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                            <button data-action="disable" data-user-info="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']) ;?>" data-user-id="<?php echo $this->escape($user['id']);?>" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                            <button data-user-info="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']) ;?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="reset-password" type="button" class="btn btn-default" title="reset"><i class="fa fa-unlock-alt"></i></button>
                            <button data-user-info="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']) ;?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

                    </div>
                <?php
            } else {
                ?>
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                            <a 
                                    href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
                                    type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                            <button data-user-info="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']) ;?>" data-action="enable" data-user-id="<?php echo $this->escape($user['id']);?>" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                            <button data-user-info="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']) ;?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="reset-password" type="button" class="btn btn-default" title="reset"><i class="fa fa-unlock-alt"></i></button>
                            <button data-user-info="<?php echo $this->escape($user['first_name']) . " " . $this->escape($user['last_name']) ;?>" data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

                    </div>
                <?php
            }
            
            
            $this->placeholder('actions')->captureEnd();
            
            $row[] = $this->placeholder('actions')->toString();
        } else {
            $row[] = $user[$columnName];
        }
        
        
    }
    
    
//    $row[] = $user['status'];
//    $row[] = $user['username'];
//    $row[] = $user['first_name'];
//    $row[] = $user['last_name'];
//    $row[] = $user['email'];
//    $row[] = '';
            
    
    $datatableJson['data'][] = $row;
}

echo $this->json($datatableJson);


