<?php 
$this->headTitle("Profile - change password");
?>


<div class="page-header">
  <h1>Profile <small>change password</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
                
        <div class="panel panel-default">
            <div class="panel-heading text-right">
            
                <div class="btn-group" role="group" aria-label="...">
                    <a class="btn btn-default"
                       href="<?php echo $this->url( array("controller" => 'admin_profile', 'action' => 'edit'), 'default', true);?>"
                       ><i class="fa fa-user"></i> Edit Profile</a>
                </div>
            
            </div>
            <div class="panel-body">
                
                

                <form class="form-horizontal">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Change Password</legend>

                        <!-- Password input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_password">New Password</label>
                            <div class="col-md-4">
                                <input id="new_password" name="new_password" placeholder="enter new password" class="form-control input-md" required="" type="password">
                                <span class="help-block">min 5 max 255 characters</span>
                            </div>
                        </div>

                        <!-- Password input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_password_confirm">Confirm new password</label>
                            <div class="col-md-4">
                                <input id="new_password_confirm" name="new_password_confirm" placeholder="confirm new password" class="form-control input-md" required="" type="password">

                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="button1id"></label>
                            <div class="col-md-8">
                                <button id="button1id" name="button1id" class="btn btn-default">Cancel</button>
                                <button id="button2id" name="button2id" class="btn btn-success">Change</button>
                            </div>
                        </div>

                    </fieldset>
                </form>

                
                
                
                
                
            </div>
        </div>
        
    </div>    
</div>