<?php 
$this->headTitle("Profile - edit profile");
?>


<div class="page-header">
  <h1>Profile <small>Edit Profile</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        
        <div class="panel panel-default">
            <div class="panel-heading text-right">
            
                <div class="btn-group" role="group" aria-label="...">
                    <a class="btn btn-default"
                       href="<?php echo $this->url( array("controller" => 'admin_profile', 'action' => 'changepassword'), 'default', true);?>"
                       ><i class="fa fa-key"></i> Change password</a>
                </div>
            
            </div>
            <div class="panel-body">
                

                <form class="form-horizontal">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit profile</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="first_name">First Name</label>  
                            <div class="col-md-4">
                                <input id="first_name" name="first_name" placeholder="enter member's first name" class="form-control input-md" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="last_name">Last Name</label>  
                            <div class="col-md-4">
                                <input id="last_name" name="last_name" placeholder="enter member's last name" class="form-control input-md" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                <input id="email" name="email" placeholder="enter member's email" class="form-control input-md" type="text">
                                <span class="help-block">user@domain</span>  
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="button1id"></label>
                            <div class="col-md-8">
                                <button id="button1id" name="button1id" class="btn btn-default">Cancel</button>
                                <button id="button2id" name="button2id" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>

                
                
                
            </div>
        </div>
        
        
        
    </div>
</div>



