<?php

$this->headTitle('Contact');

?>
		<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Contact</span> 
						<small>No project too big or small, get in touch!</small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<div class="block">
					<div class="row">
                                                <div class='col-sm-12'>
                                                    <div class="col-sm-2">
                                                    <img alt="<?php echo $this->escape($this->member['first_name']);?>" class="img-polaroid" src="<?php echo $this->memberImgUrl($this->member);?>">
                                                    </div>
                                                    <div class="col-sm-10 ">
                                                        <h3><?php echo $this->escape($this->member['first_name'] . ' ' . $this->member['last_name']);?></h3>
                                                    </div>
                                                </div>
						<div class="col-sm-6">
							<form action="#" id="contact-form">
								<div class="form-group">
									<input type="text" placeholder="Name" class="form-control">
								</div>
								<div class="form-group">
									<input type="email" placeholder="Email" class="form-control">
								</div>
								<div class="form-group">
									<textarea placeholder="Message" class="form-control" rows="15"></textarea>
								</div>
								<input type="button" value="Send Message" class="btn btn-primary">
							</form>
						</div>
						<div class="col-sm-6">
							<h3 class="block-title sub-title">
								<span>Other Ways To Get In Touch</span>
							</h3>
							<p><abbr title="Phone">P</abbr>: 011/3210-112</p>
							<p><abbr title="Fax">F</abbr>: 011/3210-112</p>
							<p><abbr title="Email">E</abbr>: office@cubes.rs</p>
							<p><abbr title="Address">A</abbr>: Bulevar Milutina Milankovića 181, 11000 Beograd</p>
							<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2829.532768204917!2d20.40871181408846!3d44.83108245805062!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x75b85805b18d2886!2zNDTCsDQ5JzUxLjkiTiAyMMKwMjQnMzYuNSJF!5e0!3m2!1sen!2srs!4v1466672173897" width="300" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
							<a href="https://maps.google.co.uk/maps?q=London&amp;ie=UTF8&amp;hq=&amp;hnear=London,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=51.510238,-0.127029&amp;spn=0.042735,0.102654&amp;z=12&amp;">
								<img class="img-polaroid" alt="Location map" src="/img/misc/map.png">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>